# Generated by Django 5.0.6 on 2025-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveringValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_status', models.CharField(choices=[('red-stable', 'Red - Stable'), ('red-improving', 'Red - Improving'), ('red-worse', 'Red - Getting Worse'), ('yellow-stable', 'Yellow - Stable'), ('yellow-improving', 'Yellow - Improving'), ('yellow-worse', 'Yellow - Getting Worse'), ('green-stable', 'Green - Stable'), ('green-improving', 'Green - Improving'), ('green-worse', 'Green - Getting Worse')], max_length=20)),
                ('reason', models.TextField()),
                ('improvement', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
