# Generated by Django 5.0.6 on 2025-04-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('department_leader', 'Department Leader'), ('team_leader', 'Team Leader'), ('senior_manager', 'Senior Manager'), ('admin', 'Admin')], max_length=20),
        ),
    ]
