# Generated by Django 5.0.6 on 2025-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Engineer', 'Engineer'), ('Department Leader', 'Department Leader'), ('Team Leader', 'Team Leader'), ('Senior Manager', 'Senior Manager'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
